#!/usr/bin/env bash
# Build a JSON bundle from docs/ and create matching Plane Pages on the server.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ATLAS_ROOT="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"
LIB_DIR="${SCRIPT_DIR}/lib"
ENV_FILE="${SCRIPT_DIR}/../.env"
ORCHESTRATOR_ENV="${ATLAS_ROOT}/.orchestrator/.env"

WRITE_MANIFEST=false
if [[ "${1:-}" == "--write-manifest" ]]; then
  WRITE_MANIFEST=true
fi

load_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    set +a
  fi
  if [[ -f "${ORCHESTRATOR_ENV}" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "${ORCHESTRATOR_ENV}"
    set +a
  fi
}

load_env

: "${PLANE_PROJECT_ID:?PLANE_PROJECT_ID is required}"
PLANE_SSH_HOST="${PLANE_SSH_HOST:-89.223.122.237}"
PLANE_SSH_USER="${PLANE_SSH_USER:-root}"
PLANE_SSH_KEY="${PLANE_SSH_KEY:-${HOME}/.ssh/id_rsa}"
PLANE_COMPOSE_DIR="${PLANE_COMPOSE_DIR:-/opt/plane/plane-app}"

DOCS_ROOT="${ATLAS_ROOT}/docs"
BUNDLE_FILE="$(mktemp)"
RESULT_FILE="$(mktemp)"
REMOTE_PY="$(mktemp)"
trap 'rm -f "${BUNDLE_FILE}" "${RESULT_FILE}" "${REMOTE_PY}"' EXIT

echo "Building page bundle from ${DOCS_ROOT}..." >&2
LIB_DIR="${LIB_DIR}" DOCS_ROOT="${DOCS_ROOT}" python3 <<'PY' > "${BUNDLE_FILE}"
import json, os, sys
from pathlib import Path

sys.path.insert(0, os.environ["LIB_DIR"])
from md_to_html import md_to_html

docs_root = Path(os.environ["DOCS_ROOT"])

def page_name(path: Path) -> str:
    if path.name == "index.md":
        return "Memory Bank"
    stem = path.stem
    if stem.startswith("#"):
        return f"ATLASQUANT-{stem.lstrip('#')}"
    if stem.startswith("-"):
        return f"ATLASQUANT-{stem.lstrip('-')}"
    return stem.replace("_", " ").replace("-", " ").title()

def build_tree(base: Path, rel_parts: tuple[str, ...]) -> dict:
    node: dict = {"__files__": {}}
    for child in sorted(base.iterdir()):
        if child.name.startswith(".") or child.name == "plane-pages":
            continue
        if child.is_dir():
            node[child.name] = build_tree(child, rel_parts + (child.name,))
        elif child.suffix == ".md":
            rel = str(Path("docs").joinpath(*rel_parts, child.name))
            text = child.read_text(encoding="utf-8")
            node["__files__"][rel] = {
                "name": page_name(child),
                "html": md_to_html(text),
            }
    return node

tree = build_tree(docs_root, ())
root_files = tree.pop("__files__", {})
print(json.dumps({"tree": tree, "root_files": root_files}))
PY

echo "Uploading to Plane (${PLANE_SSH_HOST})..." >&2
python3 <<PY > "${REMOTE_PY}"
import json, textwrap
from pathlib import Path

bundle = json.loads(Path("${BUNDLE_FILE}").read_text())
remote = Path("${LIB_DIR}/plane_pages_remote.py").read_text()
remote = remote.replace("from __future__ import annotations\\n", "")
remote = remote.split('if __name__ == "__main__":')[0]
header = '''import json
from plane.db.models import Page, Project, ProjectPage
from django.contrib.auth import get_user_model
'''
body = header + "\\n".join(
    line for line in remote.splitlines()
    if not line.startswith("from plane.db.models") and not line.startswith("from django.contrib.auth")
)
footer = f"print(json.dumps(migrate_from_bundle({json.dumps(bundle)})))"
Path("${REMOTE_PY}").write_text(body + "\\n" + footer + "\\n")
PY

scp -i "${PLANE_SSH_KEY}" -q "${REMOTE_PY}" \
  "${PLANE_SSH_USER}@${PLANE_SSH_HOST}:/tmp/atlasquant_pages_migrate.py"

ssh -n -i "${PLANE_SSH_KEY}" "${PLANE_SSH_USER}@${PLANE_SSH_HOST}" \
  "PLANE_PROJECT_ID=${PLANE_PROJECT_ID} docker compose --env-file ${PLANE_COMPOSE_DIR}/plane.env \
   -f ${PLANE_COMPOSE_DIR}/docker-compose.yaml exec -T api \
   python manage.py shell < /tmp/atlasquant_pages_migrate.py" > "${RESULT_FILE}"

ssh -i "${PLANE_SSH_KEY}" "${PLANE_SSH_USER}@${PLANE_SSH_HOST}" \
  "rm -f /tmp/atlasquant_pages_migrate.py"

echo "Migration result:" >&2
python3 -m json.tool "${RESULT_FILE}"

if [[ "${WRITE_MANIFEST}" == true ]]; then
  MANIFEST="${ATLAS_ROOT}/docs/plane-pages/manifest.yml"
  mkdir -p "$(dirname "${MANIFEST}")"
  RESULT_FILE="${RESULT_FILE}" MANIFEST="${MANIFEST}" python3 <<'PY'
import json, os
from pathlib import Path

data = json.load(open(os.environ["RESULT_FILE"]))
pages = data["pages"]
lines = [
    "# Plane Pages manifest — auto-generated by migrate-docs-to-plane-pages.sh",
    f"project_id: {data['project_id']}",
    f"workspace: {data['workspace']}",
    "external_source: atlasquant-docs",
    "pages:",
]
for rel, pid in sorted(pages.items()):
    lines.append(f'  "{rel}": {pid}')
Path(os.environ["MANIFEST"]).write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {os.environ['MANIFEST']}")
PY
fi
